# Generated by Django 4.1 on 2022-09-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('name_fr_ca', models.CharField(max_length=400, null=True)),
                ('name_en_ca', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('name_fr_ca', models.CharField(max_length=400, null=True)),
                ('name_en_ca', models.CharField(max_length=400, null=True)),
                ('definition', models.TextField()),
                ('definition_fr_ca', models.TextField(null=True)),
                ('definition_en_ca', models.TextField(null=True)),
                ('examples', models.TextField()),
                ('examples_fr_ca', models.TextField(null=True)),
                ('examples_en_ca', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Qualities',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('name_fr_ca', models.CharField(max_length=400, null=True)),
                ('name_en_ca', models.CharField(max_length=400, null=True)),
                ('description', models.TextField()),
                ('description_fr_ca', models.TextField(null=True)),
                ('description_en_ca', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_detection', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cities_light.city')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signal')),
            ],
        ),
        migrations.CreateModel(
            name='SignalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.BooleanField()),
                ('primary', models.BooleanField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.contact')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signal')),
            ],
            options={
                'unique_together': {('primary', 'signal')},
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='contact',
            field=models.ManyToManyField(through='signals.SignalContact', to='signals.contact'),
        ),
        migrations.AddField(
            model_name='signal',
            name='location',
            field=models.ManyToManyField(through='signals.SignalLocation', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='signal',
            name='source',
            field=models.ManyToManyField(to='signals.source'),
        ),
        migrations.AddField(
            model_name='contact',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='signals.program'),
        ),
    ]
