# Generated by Django 4.1 on 2022-09-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signalcontact',
            unique_together={('creator', 'signal'), ('primary', 'signal')},
        ),
    ]
